### ISSUE TITLE
Repo hảo quá

### ISSUE THREAD

**Issue by daominh89** [NotchApple1703/Bua.exe#1]
Mong chủ tus (@NotchApple1703) review nhẹ để cài về máy tự hủy =)

**Comment by NotchApple1703** [comment]
Bạn có thể lên facebook của mình https://www.facebook.com/notchapple1703, mình có up 1 vid test búa.exe :)

**Comment by NotchApple1703** [comment]
> Mong chủ tus (@NotchApple1703) review nhẹ để cài về máy tự hủy =)

Do tool này cũng đc làm từ công nghệ lõi như hãng B nên khả năng duy nhất của nó là xóa system32 :)

**Comment by daominh89** [comment]
Mình close issue nha
